spring:
  application:
    name : urlShortnerApi

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000
      jedis:
        pool:
            max-active: 10
            max-idle: 5
            min-idle: 1
            max-wait: -1

  # Casandra configuration
  cassandra:
    keySpaceName : url_shortener
    contactPoints : localhost
    port : 9042
    local-datacenter : datacenter1
    schema-action : RECREATE
#    schema-action : CREATE_IF_NOT_EXISTS
    username : cassandra
    password : cassandra