spring:
  application:
    name : urlShortnerApi
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000
      jedis:
        pool:
            max-active: 10
            max-idle: 5
            min-idle: 1
            max-wait: -1

  # Casandra configuration
  cassandra:
    keySpaceName : url_shortener
    contactPoints : localhost
    port : 9042
    local-datacenter : datacenter1
    schema-action : RECREATE
#    schema-action : CREATE_IF_NOT_EXISTS
    username : cassandra
    password : cassandra

management:
    endpoints:
        web:
          exposure:
            include: health, info, prometheus, metrics
    tracing:
      sampling:
        probability: 1.0
    zipkin:
      tracing:
        endpoint: http://localhost:9411/api/v2/spans
    metrics:
      export:
        prometheus:
          enabled: true
      tags:
        application: ${spring.application.name}
      distribution:
        percentiles-histogram:
          http.server.requests: true

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

server:
  port: 8081